fixup! Add CI for Base Browser
This reverts commit 1d1ea9c7bfa8930b5bbc928a70054c4971562347.

diff --git a/.gitlab/ci/mixins.yml b/.gitlab/ci/mixins.yml
--- a/.gitlab/ci/mixins.yml
+++ b/.gitlab/ci/mixins.yml
@@ -52,8 +52,12 @@
         return $fetch_exit
       }
 
-      fetch_with_timeout origin "merge-requests/${CI_MERGE_REQUEST_IID}/head" || exit 1
+      if ! fetch_with_timeout origin "${CI_COMMIT_BRANCH:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"; then
+        echo "Fetching failed for branch ${CI_COMMIT_BRANCH:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}."
+        echo "Attempting to fetch the merge request branch, assuming this pipeline is not running in a fork."
 
+        fetch_with_timeout origin "merge-requests/${CI_MERGE_REQUEST_IID}/head" || exit 1
+      fi
     - git checkout FETCH_HEAD
 
 .with-local-repo-pwsh:
